var firstName = "Trey"
var lastName = "Marshall"
var age = "30"
var date = "11082022"
var isWorking = "true"
var isScared = "false"
var consolelog;(firstName) = "Kelly"
var consolelog;(lastName) = "B"